select * from customer
limit 10;

--01.what is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) as revenue
from customer
group by gender;

--02.which customer used a discount but still spent more than average purchase amount?
select customer_id,purchase_amount from customer
where discount_applied='Yes' and 
purchase_amount>=(select avg(purchase_amount) from customer);

--03.which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating::numeric),2) as average_highest_rating
from customer
group by item_purchased
order by avg(review_rating) DESC
limit 5;

--04.compare the average purchase amounts between standard and express shipping?
select shipping_type,round(avg(purchase_amount),2) as avg_purchase
from customer 
where shipping_type in ('Standard','Express')
group by shipping_type;

--05.do subscribers spend more? compare average total and total revenue
--between subscribers and non subscribers?
select subscription_status,
count(customer_id) as total_customers,
sum(purchase_amount) as total_revenue,
round(avg(purchase_amount),2)as avg_amount
from customer
group by subscription_status 
order by total_revenue ,total_customers;

--06.which products have highest percentage of purchases with discounts applied?
select item_purchased,
round(100*sum(case when discount_applied='Yes' then 1 else 0 
end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate DESc
limit 5;


--07.segment customers into new,returning and loyal based on their total
--number of previous purchase and show the count of each segmant?
with customer_type as (
select customer_id,previous_purchases,
case 
   when previous_purchases=1 then 'New'
   when previous_purchases between 2 and 10 then 'Returning'
   else 'Loyal'
end as customer_segment
from customer)

select customer_segment,count(*) as total_purchases
from customer_type
group by customer_segment;


--08.what are the top 3 most purchased product within each category?
with item_count as(
select category,item_purchased,
count(customer_id) as total_orders,
Row_number() over(partition by category 
order by count(customer_id) desc) as item_rank from customer
group by category,item_purchased
)


select item_rank,category,item_purchased,total_orders from item_count
where item_rank<=3;


--09.are customers who are repeated buyers(more than 5 previous purchases)
--also likely to subscibe?
select subscription_status,count(customer_id)as repeated_customers from customer
where previous_purchases>5
group by subscription_status;

--10.what is the revenue generated by age group?
select age_group,sum(purchase_amount) as total_revenue from customer
group by age_group
order by total_revenue DESC







